split_ratio: 0.10
train_batch_size: 32
test_batch_size: 32
predict_batch_size: 1
train: True
test: False
model_params:
  lr: 0.001
  weight_decay: 0.0001
  gamma: 0.95
  hidden_size: 32
  dense_size: 64
  num_layers: 5
  pooling: False
  gf_incl: False
  random_state: 42
